export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

export const PRODUCT_DETAILS_REQUEST = "PRODUC_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCESS = "PRODUC_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUC_DETAILS_FAIL";

export const PRODUCT_DELETE_REQUEST = "PRODUC_DELETE_REQUEST";
export const PRODUCT_DELETE_SUCCESS = "PRODUC_DELETE_SUCCESS";
export const PRODUCT_DELETE_FAIL = "PRODUC_DELETE_FAIL";

export const PRODUCT_CREATE_REQUEST = "PRODUC_CREATE_REQUEST";
export const PRODUCT_CREATE_SUCCESS = "PRODUC_CREATE_SUCCESS";
export const PRODUCT_CREATE_FAIL = "PRODUC_CREATE_FAIL";
export const PRODUCT_CREATE_RESET = "PRODUC_CREATE_RESET";

export const PRODUCT_UPDATE_REQUEST = "PRODUC_UPDATE_REQUEST";
export const PRODUCT_UPDATE_SUCCESS = "PRODUC_UPDATE_SUCCESS";
export const PRODUCT_UPDATE_FAIL = "PRODUC_UPDATE_FAIL";
export const PRODUCT_UPDATE_RESET = "PRODUC_UPDATE_RESET";

export const PRODUCT_CREATE_REVIEW_REQUEST = "PRODUC_CREATE_REVIEW_REQUEST";
export const PRODUCT_CREATE_REVIEW_SUCCESS = "PRODUC_CREATE_REVIEW_SUCCESS";
export const PRODUCT_CREATE_REVIEW_FAIL = "PRODUC_CREATE_REVIEW_FAIL";
export const PRODUCT_CREATE_REVIEW_RESET = "PRODUC_CREATE_REVIEW_RESET";

export const PRODUCT_TOP_REQUEST = "PRODUC_TOP_REQUEST";
export const PRODUCT_TOP_SUCCESS = "PRODUC_TOP_SUCCESS";
export const PRODUCT_TOP_FAIL = "PRODUC_TOP_FAIL";
